import { Injectable } from '@angular/core';
import { forkJoin, Observable } from 'rxjs';
import { MailResponse, MailService } from './mail.service';

export interface Participant {
  name: string;
  email: string;
  picked?: Participant;
}

@Injectable()
export class DrawService {
  constructor(private mailService: MailService) {}

  sendResults(participants: Participant[], creator: Participant): Observable<MailResponse[]> {
    const tasks: Observable<MailResponse>[] = [];
    participants.forEach(participant => {
      tasks.push(this.mailService.send({
        to: participant.email,
        from: 'Secret Santa Generator',
        subject: 'Secret Santa Generator Result',
        message: {
          header: '<span style="color: #3d4852; font-size: 19px; font-weight: bold;">Secret Santa Generator</span>',
          // tslint:disable
          body: `Hi :)
<br> You have been added to a Secret Santa Draw. You have picked: <b>${participant.picked.name} (${participant.picked.email})</b>.
<br> This draw was generated by ${creator.name} (${creator.email}), if you do not know this person, please ignore this email.
<br> Save this email carefully, because there is no way to find this information if lost.
<br> <a href="https://secretsantagenerator.kiosoft.ca/">secretsantagenerator.kiosoft.ca</a>`,
          // tslint:enable
        },
      }));
    });

    return forkJoin(tasks);
  }
}
